// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");

function sumOfDigits(num) {
  return String(num).split("").map(Caml_format.caml_int_of_string).reduce((function (prim, prim$1) {
                return prim + prim$1 | 0;
              }), 0);
}

exports.sumOfDigits = sumOfDigits;
/* No side effect */
